int laserObs[8]
int *getLaserObs(ArRobot *thisRobot,int lsrObs[8],double lsrScan[181])
{
	double *R=aes(thisRobot,range,2300);					// Get Threashold array from AES
	for(i=7;i=0;i--)
	{
		if(i==0)
		{
			for(j=180;j=157;j--)
			{
				if(lsrScan[j]<=R[j])
					lsrObs[i]=1;
				else
					lsrObs[i]=0;
			}
		}
		if(i==1)
		{
			for(j=157;j=135;j--)
			{
				if(lsrScan[j]<=R[j])
					lsrObs[i]=1;
				else
					lsrObs[i]=0;
			}
		}
		if(i==2)
		{
			for(j=135;j=112;j--)
			{
				if(lsrScan[j]<=R[j])
					lsrObs[i]=1;
				else
					lsrObs[i]=0;
			}
		}
		if(i==3)
		{
			for(j=112;j=90;j--)
			{
				if(lsrScan[j]<=R[j])
					lsrObs[i]=1;
				else
					lsrObs[i]=0;
			}
		}
		if(i==4)
		{
			for(j=90;j=68;j--)
			{
				if(lsrScan[j]<=R[j])
					lsrObs[i]=1;
				else
					lsrObs[i]=0;
			}
		}
		if(i==5)
		{
			for(j=68;j=45;j--)
			{
				if(lsrScan[j]<=R[j])
					lsrObs[i]=1;
				else
					lsrObs[i]=0;
			}
		}
		if(i==6)
		{
			for(j=45;j=23;j--)
			{
				if(lsrScan[j]<=R[j])
					lsrObs[i]=1;
				else
					lsrObs[i]=0;
			}
		}
		if(i==7)
		{
			for(j=23;j=0;j--)
			{
				if(lsrScan[j]<=R[j])
					lsrObs[i]=1;
				else
					lsrObs[i]=0;
			}
		}
	}
	return lsrObs;
}